### ISSUE TITLE
VanillaFurnitureExpanded.CompProperties_MountableOnWall is incompatible with Replace Stuff

### ISSUE THREAD

**Issue by Garethp** [Owlchemist/simple-utilities-wall#1]
Adding [VanillaFurnitureExpanded.CompProperties_MountableOnWall is incompatible with Replace Stuff](https://github.com/Owlchemist/simple-utilities-wall/blob/master/Patches/PatchVanilla.xml#L42) while having Replace Stuff loaded breaks the ability to replace the wall under the cooler without  destroying the cooler. Could you please add a `PatchOperationFindMod` to check that Replace Stuff isn't loaded before adding that comp?

**Comment by Owlchemist** [comment]
Hey sorry I didn't see this issue on the git until now (github why aren't you notifying me about this stuff?). Anyway this should have already been long fixed, so closing.
